services:
  app:
    image: php:8.2-fpm
    volumes:
      - ./src:/var/www/html
    expose:
      - 9000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webdev
      MYSQL_USER: webuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    links:
      - app:app

volumes:
  db_data: